project:
  type: website
  output-dir: docs
  
  
website:
  title: "Genome Sequence Analysis Course"
  navbar:
    logo: "_extensions/img/WCS_Logo-Primary_Black.jpg"
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: welcome.qmd
        text: Learning paths
      - text: Modules
        menu:
          - href: course_modules/Module1/module1.qmd
            text: "File formats"
          - href: course_modules/Module2/module2.qmd
            text: "Reads alignment"
          - href: course_modules/Module3/module3.qmd
            text: "Variant calling"
          - href: course_modules/Module4/module4.qmd
            text: "Structural Variation Calling"
          - href: course_modules/Module5/module5.qmd
            text: "Genome assembly"
          - href: course_modules/Glossary/glossary.qmd
            text: "Glossary of terms"
      - text: Informatics Guide
        menu:
          - href: course_modules/VM_guide/VM_Guide.qmd
            text: "How to setup a VM"
          - href: course_modules/VM_guide/Software_list.qmd
            text: "Software list"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "File formats"
        contents:
          - course_modules/Module1/module1.qmd
          - course_modules/Module1/module1_manual.qmd
          - course_modules/Module1/module1_exercises.qmd
          - course_modules/Module1/module1_solutions.qmd
          - course_modules/Module1/module1_instructor_notes.qmd
          - course_modules/Module1/module1_datasets.qmd
          - course_modules/Module1/module1_platform_guidance.qmd
      - section: "Read alignment"
        contents:
          - course_modules/Module2/module2.qmd
          - course_modules/Module2/module2_manual.qmd
          - course_modules/Module2/module2_exercises.qmd
          - course_modules/Module2/module2_solutions.qmd
          - course_modules/Module2/module2_instructor_notes.qmd
          - course_modules/Module2/module2_datasets.qmd
          - course_modules/Module2/module2_platform_guidance.qmd
      - section: "Variant calling"
        contents:
          - course_modules/Module3/module3.qmd
          - course_modules/Module3/module3_manual.qmd
          - course_modules/Module3/module3_exercises.qmd
          - course_modules/Module3/module3_solutions.qmd
          - course_modules/Module3/module3_instructor_notes.qmd
          - course_modules/Module3/module3_datasets.qmd
          - course_modules/Module3/module3_platform_guidance.qmd
      - section: "Structural Variation Calling"
        contents:
          - course_modules/Module4/module4.qmd
          - course_modules/Module4/module4_manual.qmd
          - course_modules/Module4/module4_exercises.qmd
          - course_modules/Module4/module4_solutions.qmd
          - course_modules/Module4/module4_instructor_notes.qmd
          - course_modules/Module4/module4_datasets.qmd
          - course_modules/Module4/module4_platform_guidance.qmd
      - section: "Genome Assembly"
        contents:
          - course_modules/Module5/module5.qmd
          - course_modules/Module5/module5_manual.qmd
          - course_modules/Module5/module5_exercises.qmd
          - course_modules/Module5/module5_solutions.qmd
          - course_modules/Module5/module5_instructor_notes.qmd
          - course_modules/Module5/module5_datasets.qmd
          - course_modules/Module5/module5_platform_guidance.qmd
      - section: "How to setup your VM"
        contents:
          - course_modules/VM_guide/VM_Guide.qmd
          - course_modules/VM_guide/Software_list.qmd
      - section: 'Contributors'
        contents:
          - "meet the team.qmd"
  
  page-navigation: true 
  page-footer: 
    left: "This work is licensed under a Creative Commons Attribution 4.0 International License. Reuse is encouraged with acknowledgement" 
  search:
    location: navbar
    type: textbox

output:
  html_document:
    highlight: pygments
    css: "_extensions/styles.css"
    toc: true
    toc_float:
      collapsed: false

format:
  html:
    theme:
      light: flatly
      dark: darkly
      #light: [theme_lter-edu-light, _extensions/lter/lter_scss-theme/theme_lter-edu-light.scss]
      #dark: [theme_lter-edu-dark, _extensions/lter/lter_scss-theme/theme_lter-edu-dark.scss]
    anchor-sections: true
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true

editor: visual

execute:
  freeze: auto
  
sidebar:
  contents: auto

link-external-newwindow: true
